services:
  demo_mongo_cache_service:
    image: mongo
    container_name: demo_mongo_cache_service
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_cache_data_db:/data/db
      - mongo_cache_config_db:/data/configdb
  demo_webapp_service:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    container_name: demo_webapp_service
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      MONGO_CACHE_URL : "mongodb://demo_mongo_cache_service:27017"
    depends_on:
      - demo_mongo_cache_service

volumes:
  mongo_cache_data_db:
  mongo_cache_config_db:
